In [12]:
l=input().split()
l= list(map(int,l))
s=len(l)
i=0
for i in range(s):
    if((l[i]%3==0)or(l[i]%5==0)or(l[i]%7==0)):
        print(l[i])

12 13 45 89
12
45


# Data science
### NumPy - Numerical Python
### Pandas - DataFrames and Series
### MatplotLib - Visualization
### Seaborn - makes difficult task easy
### IPython - Interactive Python 

In [2]:
import numpy as np 
a  = np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [19]:
a_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(a_2d)
type(a_2d)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [18]:
li = [1,3,5,7,8]
l_a = np.array(li)
print(l_a)

[1 3 5 7 8]


### ndim - returns the no of dimenisons of the array
### shape - returns the length of array
### size - size of an array
### itemsize - returns the size of an element
### dtype - returns the type of an array

In [20]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
 n =  np.random.randint(0,50,10)
print(n)
print(n.ndim)
print(n.shape)
print(n.size)
print(n.itemsize)
print(n.dtype)

[26 11 42 37 11 34  8 14  9 35]
1
(10,)
10
4
int32


In [30]:
n =  np.random.randint(0,50,size = 12).reshape(3,4)
print(n)
n.ndim
n[::-1]

[[31 11 37 26]
 [30 37 29 31]
 [41 27 33 29]]


array([[41, 27, 33, 29],
       [30, 37, 29, 31],
       [31, 11, 37, 26]])

In [36]:
n = np.ones(9)
m = np.zeros(8)
print(n)
print(m)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
k = np.linspace(0,2,7)
print(k)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]


In [42]:
f = np.full((2,2),9)
print(f)

[[9 9]
 [9 9]]


In [44]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
em = np.empty((5,2))
print(em)

[[3.56043053e-307 1.60219306e-306]
 [7.56571288e-307 1.89146896e-307]
 [1.37961302e-306 1.05699242e-307]
 [8.01097889e-307 1.24610723e-306]
 [8.34444713e-308 2.29179042e-312]]


In [47]:
em = np.empty(8)
em

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [54]:
c = np.array([[[2,4,5],[9,56,4]]])
print(c)
c.ndim
c.reshape(1,6)

[[[ 2  4  5]
  [ 9 56  4]]]


array([[ 2,  4,  5,  9, 56,  4]])

In [53]:
c.ravel()

array([ 2,  4,  5,  9, 56,  4])

In [3]:
a = 34
b = 67
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(100))
print(np.sin(a))
print(np.cos(b))
print(np.exp(64))
print(np.log(4))

101
-33
2278
0.5074626865671642
10.0
0.5290826861200238
-0.5177697997895051
6.235149080811617e+27
1.3862943611198906


In [16]:
a = np.arange(18).reshape(3,6)
print(a)
print("max",a.max())
print("min",a.min(axis = 0 ))
print(a.max(axis=1))
print("sum",a.sum())
print("cumsum",a.cumsum())
print("mean",np.mean(a))
print("median",np.median(a))
print(np.std(b))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
max 17
min [0 1 2 3 4 5]
[ 5 11 17]
sum 153
cumsum [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153]
mean 8.5
median 8.5
0.0


In [17]:
sa = np.array([23,45,98,1,2,3,4,76,6754])
sa.sort()

In [18]:
sa

array([   1,    2,    3,    4,   23,   45,   76,   98, 6754])

In [24]:
s = np.array([[23,45,98],[1,2,3],[4,76,6754]])
print(s)
print("transpose \n",np.transpose(s))
s.T

[[  23   45   98]
 [   1    2    3]
 [   4   76 6754]]
transpose 
 [[  23    1    4]
 [  45    2   76]
 [  98    3 6754]]


array([[  23,    1,    4],
       [  45,    2,   76],
       [  98,    3, 6754]])

In [29]:
print(np.hsplit(s,3))
print(np.vsplit(s,3))

[array([[23],
       [ 1],
       [ 4]]), array([[45],
       [ 2],
       [76]]), array([[  98],
       [   3],
       [6754]])]
[array([[23, 45, 98]]), array([[1, 2, 3]]), array([[   4,   76, 6754]])]


In [35]:
s1 = np.array([23,45,98,1,2,3,4,76,6754,12,5,24])
s1

array([  23,   45,   98,    1,    2,    3,    4,   76, 6754,   12,    5,
         24])

In [36]:
np.hsplit(s1,3)

[array([23, 45, 98,  1]),
 array([ 2,  3,  4, 76]),
 array([6754,   12,    5,   24])]

In [38]:
s = np.array([[23,45,98],[1,2,3],[4,76,6754]])
s[0]

array([23, 45, 98])

In [45]:
print(s[0:2])
s[0:2,1]
s[2,0]

[[23 45 98]
 [ 1  2  3]]


4